app/routes.py
from flask import Blueprint, Flask, render_template, redirect, url_for, flash, get_flashed_messages, request, session, jsonify
#from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required, current_user, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, date, time
from app.forms import *
from app.models import *
from app.data import *
from app import db
from flask_bootstrap import Bootstrap5
from sqlalchemy import func, or_

import os
import pandas as pd





bp = Blueprint('main', __name__)


UPLOAD_FOLDER = 'app/static/uploads'





# Routes

@bp.route('/')
def home():
    return render_template('home.html', title='Home')



@bp.route('/attendance', methods=['GET', 'POST'])
def attendance():
    users = User.query.order_by(User.surname, User.first_name).all()
    titles = Title.query.all()
    return render_template('attendance_report.html', users=users, titles=titles)



@bp.route('/attendance/', methods=['GET', 'POST'])
def view_attendance():
    users = User.query.order_by(User.surname, User.first_name).all()
    titles = Title.query.all()
    return render_template('attendance_report.html', users=users, titles=titles)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        if User.query.filter_by(surname=form.surname.data.upper(), first_name=form.first_name.data).first():
            flash("User exists!", 'warning')
            return redirect(url_for('main.login'))
        passwd_hash = generate_password_hash(form.password.data, method='scrypt', salt_length=8)
        #print(form.category.data.id)
        is_admin = False
        if form.email.data in managers:
            is_admin = True

        new_user = User(
            title_id=form.title.data.id,
            surname=form.surname.data.upper(),
            first_name=form.first_name.data,
            email=form.email.data,
            password=passwd_hash,
            phone_number=form.phone.data,
            category_id=form.category.data.id,
            department_id=form.department.data.id,
            is_admin=is_admin
        )
        db.session.add(new_user)
        db.session.commit()
        flash(f'User {form.email.data} created.', 'success')
        return redirect(url_for('main.login'))
    return render_template('signup.html', title='Sign Up', heading='Register', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            flash(f'User with account "{form.email.data}" does not exist', 'info')
            return redirect(url_for('main.login'))
        if check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('main.home'))
    return render_template('signin.html', form=form, title='Login', heading='Login')



@bp.route('/logout')
@login_required
def logout():
    logout_user()  # This is enough to log the user out
    session.clear()  # Clears the session data safely
    return redirect(url_for('main.home'))



@bp.route('/user/add', methods=['GET', 'POST'])
def register_user():
    form = UserForm()
    if form.validate_on_submit():
        surname = form.surname.data
        first_name = form.first_name.data
        if User.query.filter_by(surname=surname.upper(), first_name=first_name).first():
            flash("User exists!", 'warning')
            return redirect(url_for('main.login'))
        db.session.add(
            User(
                title_id=form.title.data.id,
                surname=surname.upper(),
                first_name=first_name,
                category_id=form.category.data.id,
                department_id=form.department.data.id
            )
        )
        #print(f"{form.category.data.id} {form.surname.data}")
        db.session.commit()
        return redirect(url_for('main.staff_attendance'))
    return render_template('login.html', form=form, title='Add User', heading='Add User')



@bp.route('/department/add', methods=['GET', 'POST'])
def add_department():
    form = DepartmentForm()
    if form.validate_on_submit():
        if Department.query.filter_by(name=form.name.data).first():
            flash("Department exists!", 'info')
            return redirect(url_for('main.register'))
        db.session.add(
            Department(name=form.name.data)
        )
        db.session.commit()
        return redirect(url_for('main.register'))
    return render_template('register.html', form=form)



@bp.route('/report/')
def report():
    session_id = request.args.get('session_id')
    session = Session.query.get_or_404(session_id)
    attendances = Attendance.query.filter_by(session_id=session_id).all()
    return render_template('report.html', session=session, attendances=attendances)


@bp.route('/report/', methods=['GET', 'POST'])
def create_academic_year():
    session_id = request.args.get('session_id')
    session = Session.query.get_or_404(session_id)
    attendances = Attendance.query.filter_by(session_id=session_id).all()
    return render_template('report.html', session=session, attendances=attendances)





@bp.route('/exam/create-exam', methods=['GET', 'POST'])
def create_exam():
    form = ExamForm()
    if form.validate_on_submit():
        exam = Exam(
            title=form.title.data,
            #date=form.date.data,
            session_id=form.session.data.id,
            course_id=form.course.data.id
        )
        # Since QuerySelectMultipleField returns objects, no need to query again
        for programme in form.programmes.data:
            exam.programmes.append(programme)
        for venue in form.venues.data:
            exam.venues.append(venue)
            
        db.session.add(exam)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('create_exam.html', form=form, title='Schedule Exam', heading='Create Exam')



@bp.route('/exams/view', methods=['GET', 'POST'])
def view_exams():
    exams = Exam.query.all()
    return render_template('view_exams.html', title='View Exams', heading='View Exams', exams=exams)



@bp.route('/exam/edit/<int:exam_id>', methods=['GET', 'POST'])
def edit_exam(exam_id):
    form = ExamForm()
    exam = Exam.query.get_or_404(exam_id)
    if not exam:
        flash('Exam not found!', 'info')
        return redirect(url_for('main.view_exams'))
    
    # Populate form with data
    form.title.data = exam.title
    form.date.data = exam.date
    form.session.data = exam.session_id
    form.course.data = exam.course_id

    if form.validate_on_submit():
        exam = Exam(
            title=form.title.data,
            date=form.date.data,
            session_id=form.session.data,
            course_id=form.course.data
        )
        for programme_id in form.programmes.data:
            programme = Programme.query.get(programme_id)
            exam.programmes.append(programme)
        for venue_id in form.venues.data:
            venue = Venue.query.get(venue_id)
            exam.venues.append(venue)
        db.session.add(exam)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('form.html', title='Create Schedule', heading='Create Schedule', form=form)



@bp.route('/exam/delete/<int:exam_id>', methods=['GET', 'POST'])
def delete_exam(exam_id):
    exam = Exam.query.get_or_404(exam_id)
    if not exam:
        flash('Exam not found!', 'info')
        return redirect(url_for('main.view_exams'))
    db.session.delete(exam)
    db.session.commit()
    return redirect(url_for('main.view_exams'))



@bp.route('/course/create', methods=['GET', 'POST'])
def create_course():
    form = CourseForm()
    if form.validate_on_submit():
        course_code = form.course_code.data.strip()
        title = form.title.data.strip().upper()
        if not Course.query.filter_by(course_code=course_code).first():
            db.session.add(
                Course(
                    course_code=course_code,
                    title=title
                )
            )
        db.session.commit()
        flash(f"{course_code} successfully created.", 'success')
        return redirect(url_for('main.create_exam'))
    return render_template('login.html', title='Create Course', heading='Create Course', form=form)


@bp.route('/courses/create', methods=['GET', 'POST'])
def create_courses():
    data = cohss_courses
    for key,val in data.items():
        course_code = key.strip()
        title = val.strip()
        # print(course_code)
        if not Course.query.filter_by(course_code=course_code).first():
            new_course = Course(
                course_code=course_code,
                title=title
            )
            db.session.add(new_course)

    db.session.commit() # Commit all new courses after the loop
    flash('CoHSS courses created successfully.', 'success') # Optional: Add a success message
    return redirect(url_for('main.home'))





@bp.route('/user/create-title', methods=['GET', 'POST'])
def create_title():
    form = TitleForm()
    if form.validate_on_submit():
        title = form.title.data
        if not Title.query.filter_by(title=title).first():
            db.session.add(
                Title(title=title)
            )
            db.session.commit()
            flash('Title created.', 'success')
            return redirect(url_for('main.home'))
    return render_template('login.html', title='Create Title', heading='Create Title', form=form)



@bp.route('/user/create', methods=['GET', 'POST'])
def create_user():
    form=UserForm()
    if form.validate_on_submit():
        pass
    return render_template('add_user.html', title='Create User', heading='Create User', form=form)


@bp.route('/users/create', methods=['GET', 'POST'])

app/templates/create_exam.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}


<div class="container d-flex justify-content-center align-items-center min-vh-100 my-5">
    <div style="max-width: 600px;" class="login-card col-lg-4 col-md-6 col-sm-10">
            <div class=" login-form">
                <div class="text-center mb-4">
                    <h3 class="heading fw-bold">{{heading}}</h3>
                    <hr class="my-4">
                </div>
                
               <div>
                    {{render_form(form)}}
               </div>
               
            </div>

    </div>
</div>


{% endblock content %}

app/templates/exam_form.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow-lg" style="width: 700px; max-height: 90vh; overflow-y: auto;">
        <h4 class="text-center my-3">{{heading}}</h4>
        <hr class="py-3">
        <div>
           {{ render_form(form)}}
        </div>
        <hr class="pt-3">
        <div class="pt-3 text-center">
            <p>
                Course does not exist? <a href="{{url_for('main.create_course')}}">Create Course</a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/home.html
{% extends "base.html" %}


{% block title %}
    {{title}}
{% endblock %}




{% block content %}

<!-- Hero Section -->
<section class="hero-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h1 class="display-4 fw-bold mb-3">Track Invigilation Attendance </h1>
                <p class="lead mb-4">A comprehensive solution for CoHSS to efficiently manage and monitor exam attendance with real-time analytics and insights.</p>
                <div class="d-flex gap-3">
                    <a href="login.html" class="btn btn-gradient-primary btn-lg px-4 py-2">Get Started</a>
                    <a href="#features" class="btn btn-outline-secondary btn-lg px-4 py-2">Learn More</a>
                </div>
            </div>
            <div class="col-lg-6 mt-5 mt-lg-0 text-center">
                <img src="static/images/checklist2.jpg" alt="Exam Attendance System" class="img-fluid rounded shadow">
            </div>
        </div>
    </div>
</section>


<!-- Features Section -->
<section class="py-5" id="features">
    <div class="container">
        <div class="text-center mb-5">
            <h2 class="fw-bold">Key Features</h2>
            <p class="text-muted">Discover why ExamTrack is the preferred choice for institutions worldwide</p>
        </div>
        <div class="row g-4">
            <div class="col-md-6 col-lg-3">
                <div class="card h-100">
                    <div class="card-body text-center p-4">
                        <div class="icon-circle gradient-primary mx-auto mb-4">
                            <i class="fas fa-user-check text-white"></i>
                        </div>
                        <h5 class="card-title">Attendance Tracking</h5>
                        <p class="card-text">Record and verify student presence in real-time with QR codes or biometric options.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="card h-100">
                    <div class="card-body text-center p-4">
                        <div class="icon-circle gradient-secondary mx-auto mb-4">
                            <i class="fas fa-chart-line text-white"></i>
                        </div>
                        <h5 class="card-title">Analytics Dashboard</h5>
                        <p class="card-text">Gain valuable insights with comprehensive reporting and attendance statistics.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="card h-100">
                    <div class="card-body text-center p-4">
                        <div class="icon-circle" style="background: linear-gradient(135deg, var(--success-color) 0%, #169a6b 100%);">
                            <i class="fas fa-bell text-white"></i>
                        </div>
                        <h5 class="card-title">Notifications</h5>
                        <p class="card-text">Automated alerts for absentees, low attendance, and exam schedule updates.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="card h-100">
                    <div class="card-body text-center p-4">
                        <div class="icon-circle" style="background: linear-gradient(135deg, var(--warning-color) 0%, #d5a636 100%);">
                            <i class="fas fa-mobile-alt text-white"></i>
                        </div>
                        <h5 class="card-title">Mobile Integration</h5>
                        <p class="card-text">Access the system on-the-go with our responsive mobile application.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Stats Section -->
<section class="py-5 bg-white">
    <div class="container">
        <div class="text-center mb-5">
            <h2 class="fw-bold">Trusted by Leading Institutions</h2>
            <p class="text-muted">Join hundreds of educational institutions already using ExamTrack</p>
        </div>
        <div class="row g-4">
            <div class="col-md-3">
                <div class="text-center">
                    <h2 class="display-4 fw-bold text-primary">98%</h2>
                    <p class="text-muted">Accuracy Rate</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="text-center">
                    <h2 class="display-4 fw-bold text-success">500+</h2>
                    <p class="text-muted">Institutions</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="text-center">
                    <h2 class="display-4 fw-bold text-info">5M+</h2>
                    <p class="text-muted">Exams Tracked</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="text-center">
                    <h2 class="display-4 fw-bold text-warning">70%</h2>
                    <p class="text-muted">Time Saved</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- CTA Section -->
<section class="py-5" style="background: linear-gradient(120deg, #e2e5ee 0%, #f8f9fc 100%);">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="fw-bold mb-3">Ready to Streamline Your Exam Process?</h2>
                <p class="lead mb-4">Start tracking attendance efficiently and get valuable insights today.</p>
                <a href="login.html" class="btn btn-gradient-primary btn-lg px-5 py-3">Get Started Now</a>
            </div>
        </div>
    </div>
</section>



{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <!-- Use only one Bootstrap CSS source (CDN here, remove local if not needed) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- jQuery UI CSS -->
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet">
    <!-- jQuery (required for jQuery UI and potentially Bootstrap if using older versions) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- jQuery UI JS -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.home') }}"><i class="bi bi-card-checklist me-2"></i>Tally</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.home') }}">Home</a></li>
                    
                    {% if current_user and current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="reports.html">Attendance</a></li>

                    <!-- Schedule Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Schedule
                        </a>
                        <ul class="dropdown-menu bg-dark">
                            
                            <li><a class="dropdown-item" href="{{ url_for('main.staff_attendance') }}">Staff Attendance</a></li>
                            <li><a class="dropdown-item " href="{{ url_for('main.create_exam') }}">Create Exam</a></li>
                            
                        </ul>
                    </li>

                        <!-- Create Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Create
                            </a>
                            <ul class="dropdown-menu bg-dark">

                               
                                <li><a class="dropdown-item" href="{{ url_for('main.create_title') }}">Create Title</a></li>

                                <li><a class="dropdown-item" href="{{ url_for('main.create_academic_year') }}">Add Academic Year</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('main.create_session') }}">Create Session</a></li>
                            </ul>
                        </li>
                        {% endif %}


                    {% if current_user and current_user.is_authenticated %}
                    <!-- Reports Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Reports
                        </a>
                        <ul class="dropdown-menu bg-dark">
                            <li><a class="dropdown-item" href="{{ url_for('main.view_exams') }}">View Exams</a></li>
                            <li><a class="dropdown-item " href="{{ url_for('main.attendance') }}">View Attendance</a></li>
                            
                        </ul>
                    </li>
                    <li class="nav-item ps-5"><a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a></li>
                    {% else %}
                    <li class="nav-item ps-5"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>



    <div id="flash-section" class="container-fluid px-4" style="width: 400px;">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>




    <div style="min-height: 100vh;" class="container-fluid">
        {% block content %}


        {% endblock content %}
    </div>

    <!-- Footer -->
    <footer class="bg-dark footer text-white text-center py-3">
        © 2025 Attendance App. All rights reserved.
    </footer>

    <!-- Bootstrap JS (use only one source, CDN here) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    {% block scripts %}{% endblock scripts %}

    <script>
        // Automatically close flash messages after 5 seconds
        setTimeout(() => {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => {
                const bootstrapAlert = bootstrap.Alert.getOrCreateInstance(alert);
                bootstrapAlert.close();
            });
        }, 5000);
    </script>
</body>
</html>

app/templates/narrow_form.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}


<div class="container d-flex justify-content-center align-items-center min-vh-100 my-5 py-5">
    <div style="max-width: 450px;" class="login-card col-lg-4 col-md-6 col-sm-10">
            <div class=" login-form">
                <div class="text-center mb-4">
                    <h3 class="heading fw-bold">{{heading}}</h3>
                    <hr class="my-4">
                </div>
                
               <div>
                    {{render_form(form)}}
               </div>
               
            </div>

    </div>
</div>





{% endblock content %}


{% block scripts %}

<script>
    $(document).ready(function() {
        // Listen for changes on the date field
        $('#date').on('change', function() {
            var selectedDate = $(this).val();
            // Make sure a date is selected
            if (selectedDate) {
                $.ajax({
                    url: '/get_sessions',
                    type: 'GET',
                    data: { date: selectedDate },
                    dataType: 'json',
                    success: function(data) {
                        var $sessionField = $('#session');
                        // Clear current options
                        $sessionField.empty();
    
                        // Optionally, add a placeholder option
                        $sessionField.append($('<option>', { 
                            value: '',
                            text: 'Select a session'
                        }));
    
                        // Populate with new options
                        $.each(data, function(index, session) {
                            $sessionField.append($('<option>', {
                                value: session.id,
                                text: session.name
                            }));
                        });
                    },
                    error: function(xhr, status, error) {
                        console.error("Error retrieving sessions:", error);
                    }
                });
            }
        });
    });
    </script>

{% endblock scripts %}

app/templates/report.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="mb-3">Attendance Report for {{ session.name }} - {{ session.date_time }}</h1>
    <h2 class="mb-4">Venue: {{ session.venue.name }}</h2>
    {% if attendances %}
        <ul class="list-group">
            {% for attendance in attendances %}
                <li class="list-group-item">{{ attendance.user.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No attendance recorded for this session.</p>
    {% endif %}
    <a href="{{ url_for('attendance') }}" class="btn btn-primary mt-3">Back to Attendance</a>
</div>
{% endblock %}

app/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Exam Attendance - Home</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-custom">
    <div class="container">
      <a class="navbar-brand" href="#">Exam Attendance</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="report.html">Reports</a></li>
          <li class="nav-item"><a class="nav-link" href="table.html">Table View</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Hero Section -->
  <section class="hero">
    <div class="container">
      <h1 class="display-4">Welcome to Exam Attendance</h1>
      <p class="lead">Efficiently manage and track exam attendance with a sleek and responsive design.</p>
      <a href="login.html" class="btn btn-light btn-lg">Get Started</a>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container">
      <p>&copy; 2025 Exam Attendance. All rights reserved.</p>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/view_exams.html
{% extends "layout.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

<div class="container py-5">
    <h4 class="mb-4 text-center">{{ heading }}</h4>
    <div class="row">
        {% for exam in exams %}
        <div class="col-md-6 col-12 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">{{ exam.title }}</h5>
                    <h5 class="card-title text-center">{{ exam.date }} || {{ exam.session.start_time }}</h5>
                    <p class="course-title text-center"><strong>{{ exam.course.course_code }} | {{ exam.course.title }}</strong></p>
                    <hr>
                    <div class="row d-flex py-2 flex-grow-1">
                        <div class="col-6">
                            <ul>
                                {% for venue in exam.venues %}
                                <li>{{ venue.name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-6">
                            <ul>
                                {% for program in exam.programmes %}
                                <li>{{ program.name }}  {{ program.year }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="text-center pt-2">
                        <a href="{{ url_for('main.edit_exam', exam_id=exam.id) }}" class="btn btn-outline-warning">Edit</a>
                        <a href="{{ url_for('main.delete_exam', exam_id=exam.id) }}" 
                        class="btn btn-outline-danger"
                        onclick="return confirm('Are you sure you want to delete this exam?');">
                        Delete
                        </a>
                     
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

app/templates/view_sessions.html
{% extends "layout.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}

<div style="background-color: whitesmoke;" class="container mt-5 py-3 px-5">
    <h2 class="text-center bg-light my-3">{{heading}}</h2>
    {% if sessions %}
    <div style="width: 400px;" class="py-3">
        {{render_form(form)}}
    </div>
    <hr class="py-3">

    
    <table class="table table-bordered table-striped mt-4 bg-white shadow-lg">
        <thead>
            <tr class="bg-info">
                <th>Session ID</th>
                <th>Session Name</th>
                <th>Session Date</th>
                <th>Session Count</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{% if user.title_id %}{{ user.title.title }}{% endif %}</td>
                <td>{{user.surname}} {{user.first_name}}</td>
                <td>{{user.department.name}}</td>
                <td>{{user.session_count}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <div>
            <h4 class="text-center">No sessions to display.</h4>
        </div>
    {% endif %}
</div>

{% endblock content %}